
import { Order, User, OrderStatus } from './types';

export const MOCK_ORDERS: Order[] = [
  {
    id: 'ORD-001',
    title: '京东包裹',
    description: '小盒子，请从东门取',
    recipientName: '张三',
    dormitory: '南1栋-101',
    status: OrderStatus.Pending,
    price: 5,
    publisher: 'xnys2823',
    publishTime: '12:05',
    avatarUrl: 'https://picsum.photos/50/50?random=1',
    packageCount: 1,
    expressType: '日用品',
    pickupCode: '12-3-456',
    contactPhone: '13800138000',
    pickupLocation: '东门快递点',
    deadline: '13:00'
  },
  {
    id: 'ORD-002',
    title: '外卖配送',
    description: '麦当劳订单，请尽快',
    recipientName: '李四',
    dormitory: '南2栋-204',
    status: OrderStatus.Pending,
    price: 8,
    publisher: 'lp09190706',
    publishTime: '12:10',
    avatarUrl: 'https://picsum.photos/50/50?random=2',
    packageCount: 2,
    expressType: '外卖',
    pickupCode: '99-9-999',
    contactPhone: '13900139000',
    pickupLocation: '南门外卖柜',
    deadline: '12:40'
  },
  {
    id: 'ORD-003',
    title: '重书本',
    description: '箱子很重，需要小推车',
    recipientName: '王五',
    dormitory: '南3栋-305',
    status: OrderStatus.Delivering,
    price: 10,
    publisher: 'user_003',
    accepter: 'xnys2823',
    publishTime: '11:00',
    avatarUrl: 'https://picsum.photos/50/50?random=3',
    packageCount: 5,
    expressType: '贵重物品',
    pickupCode: '88-8-888',
    contactPhone: '13700137000',
    pickupLocation: '菜鸟驿站',
    deadline: '18:00'
  },
  {
    id: 'ORD-004',
    title: '鲜花',
    description: '易碎物品，请小心轻放',
    recipientName: '赵六',
    dormitory: '南1栋-102',
    status: OrderStatus.Delivered,
    price: 15,
    publisher: 'xnys2823', // Changed to current user to show in "My Posted" -> "Pending Review"
    accepter: 'user_003',
    publishTime: '09:00',
    completeTime: '09:30',
    avatarUrl: 'https://picsum.photos/50/50?random=4',
    packageCount: 1,
    expressType: '易碎品',
    pickupCode: '77-7-777',
    contactPhone: '13600136000',
    pickupLocation: '花店',
    deadline: '10:00',
    isReviewed: false // Pending review
  },
  {
    id: 'ORD-005',
    title: '生鲜水果',
    description: '一箱苹果，比较重',
    recipientName: '小明',
    dormitory: '南3栋-302',
    status: OrderStatus.Pending,
    price: 6,
    publisher: 'user_005',
    publishTime: '12:20',
    avatarUrl: 'https://picsum.photos/50/50?random=5',
    packageCount: 3,
    expressType: '生鲜冷链',
    pickupCode: '11-1-111',
    contactPhone: '13500135000',
    pickupLocation: '南门丰巢',
    deadline: '13:30'
  },
  {
    id: 'ORD-006',
    title: '唯品会包裹',
    description: '衣服，不重',
    recipientName: '小红',
    dormitory: '南4栋-405',
    status: OrderStatus.Pending,
    price: 3,
    publisher: 'user_006',
    publishTime: '12:25',
    avatarUrl: 'https://picsum.photos/50/50?random=6',
    packageCount: 1,
    expressType: '普通快递',
    pickupCode: '22-2-222',
    contactPhone: '13400134000',
    pickupLocation: '菜鸟驿站',
    deadline: '18:00'
  },
  {
    id: 'ORD-007',
    title: '电脑配件',
    description: '显卡，贵重物品，请当面交付',
    recipientName: '张伟',
    dormitory: '南5栋-512',
    status: OrderStatus.Pending,
    price: 12,
    publisher: 'user_007',
    publishTime: '12:30',
    avatarUrl: 'https://picsum.photos/50/50?random=7',
    packageCount: 1,
    expressType: '贵重物品',
    pickupCode: '33-3-333',
    contactPhone: '13300133000',
    pickupLocation: '顺丰快递点',
    deadline: '14:00'
  },
  {
    id: 'ORD-008',
    title: '几箱牛奶',
    description: '有点重，需要送上楼',
    recipientName: '李娜',
    dormitory: '南2栋-101',
    status: OrderStatus.Pending,
    price: 8,
    publisher: 'user_008',
    publishTime: '12:35',
    avatarUrl: 'https://picsum.photos/50/50?random=8',
    packageCount: 2,
    expressType: '日用品',
    pickupCode: '44-4-444',
    contactPhone: '13200132000',
    pickupLocation: '天猫超市柜',
    deadline: '15:00'
  },
  {
    id: 'ORD-009',
    title: '奶茶外卖',
    description: '一点点奶茶，冰的，请尽快',
    recipientName: '王强',
    dormitory: '南6栋-606',
    status: OrderStatus.Pending,
    price: 5,
    publisher: 'user_009',
    publishTime: '12:40',
    avatarUrl: 'https://picsum.photos/50/50?random=9',
    packageCount: 1,
    expressType: '外卖',
    pickupCode: '55-5-555',
    contactPhone: '13100131000',
    pickupLocation: '南门外卖架',
    deadline: '13:00'
  },
  {
    id: 'ORD-010',
    title: '打印文件',
    description: '非常紧急，需要立即送达',
    recipientName: '刘洋',
    dormitory: '南1栋-202',
    status: OrderStatus.Pending,
    price: 15,
    publisher: 'user_010',
    publishTime: '12:45',
    avatarUrl: 'https://picsum.photos/50/50?random=13',
    packageCount: 1,
    expressType: '重要文件',
    pickupCode: '66-6-666',
    contactPhone: '13000130000',
    pickupLocation: '打印店',
    deadline: '13:10'
  },
  {
    id: 'ORD-011',
    title: '零食大礼包',
    description: '比较大件，三个包裹',
    recipientName: '陈静',
    dormitory: '南7栋-303',
    status: OrderStatus.Pending,
    price: 7,
    publisher: 'user_011',
    publishTime: '12:50',
    avatarUrl: 'https://picsum.photos/50/50?random=14',
    packageCount: 3,
    expressType: '日用品',
    pickupCode: '77-7-777',
    contactPhone: '13911139111',
    pickupLocation: '菜鸟驿站',
    deadline: '19:00'
  },
  {
    id: 'ORD-012',
    title: '普通快递',
    description: '书本',
    recipientName: '赵敏',
    dormitory: '南8栋-404',
    status: OrderStatus.Pending,
    price: 4,
    publisher: 'user_012',
    publishTime: '12:55',
    avatarUrl: 'https://picsum.photos/50/50?random=15',
    packageCount: 1,
    expressType: '普通快递',
    pickupCode: '88-8-888',
    contactPhone: '13811138111',
    pickupLocation: '西门快递点',
    deadline: '20:00'
  },
  {
    id: 'ORD-013',
    title: '运动鞋',
    description: '得物包裹',
    recipientName: '周杰',
    dormitory: '南2栋-333',
    status: OrderStatus.Pending,
    price: 5,
    publisher: 'user_013',
    publishTime: '13:00',
    avatarUrl: 'https://picsum.photos/50/50?random=16',
    packageCount: 1,
    expressType: '普通快递',
    pickupCode: '99-9-999',
    contactPhone: '13722237222',
    pickupLocation: '东门',
    deadline: '18:30'
  },
  {
    id: 'ORD-014',
    title: '蛋糕',
    description: '生日蛋糕，极其易碎',
    recipientName: '吴依',
    dormitory: '南5栋-111',
    status: OrderStatus.Pending,
    price: 20,
    publisher: 'user_014',
    publishTime: '13:05',
    avatarUrl: 'https://picsum.photos/50/50?random=17',
    packageCount: 1,
    expressType: '易碎品',
    pickupCode: '00-0-000',
    contactPhone: '13633336333',
    pickupLocation: '校外蛋糕店',
    deadline: '17:00'
  },
  {
    id: 'ORD-015',
    title: '大桶水',
    description: '一桶水，送上5楼',
    recipientName: '郑爽',
    dormitory: '南3栋-501',
    status: OrderStatus.Pending,
    price: 8,
    publisher: 'user_015',
    publishTime: '13:10',
    avatarUrl: 'https://picsum.photos/50/50?random=18',
    packageCount: 1,
    expressType: '日用品',
    pickupCode: '12-1-212',
    contactPhone: '13544435444',
    pickupLocation: '一楼超市',
    deadline: '14:00'
  }
];

export const MOCK_USERS: User[] = [
  {
    id: 'U001',
    username: 'xnys2823',
    phone: '150xxxxx769',
    address: '南1栋',
    gender: 'Male',
    avatarUrl: 'https://picsum.photos/100/100?random=10',
    ordersTaken: 199,
    ordersPosted: 76
  },
  {
    id: 'U002',
    username: 'lp09190706',
    phone: '133xxxxx199',
    address: '南2栋',
    gender: 'Male',
    avatarUrl: 'https://picsum.photos/100/100?random=11',
    ordersTaken: 45,
    ordersPosted: 12
  },
  {
    id: 'U003',
    username: 'campus_queen',
    phone: '138xxxxx888',
    address: '南3栋',
    gender: 'Female',
    avatarUrl: 'https://picsum.photos/100/100?random=12',
    ordersTaken: 10,
    ordersPosted: 150
  }
];

export const DORM_BUILDINGS = [
  '南1栋', '南2栋', '南3栋', '南4栋', '南5栋', '南6栋', '南7栋', '南8栋'
];

export const EXPRESS_TYPES = [
  '普通快递', '外卖', '易碎品', '贵重物品', '重要文件', '生鲜冷链', '日用品'
];

export const MOCK_REVIEWS = [
  { id: 1, user: 'xnys2823', rating: 5, content: '接单速度很快，非常准时！', time: '10分钟前' },
  { id: 2, user: 'campus_user', rating: 4, content: '服务态度很好，送到了门口。', time: '2小时前' },
  { id: 3, user: 'student_a', rating: 5, content: '非常感谢，解了燃眉之急。', time: '昨天' }
];